Update git-actions.yml

diff --git a/.github/workflows/git-actions.yml b/.github/workflows/git-actions.yml
--- a/.github/workflows/git-actions.yml
+++ b/.github/workflows/git-actions.yml
@@ -14,6 +14,12 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
           
-      - name: Echo the greeting's time
-        run: echo 'The time was ${{ http://sonarcloud.io/api/qualitygates/project_status?projectKey=bcbrunocesar_react-hooks-ts }}.'       
+      - name: SonarCloudResult
+        run: |
+          BT_STATUS=$(curl -s http://sonarcloud.io/api/qualitygates/project_status?projectKey=bcbrunocesar_react-hooks-ts |  jq --raw-output '.status')
+          echo "SonarCloud API: $BT_STATUS"
+          if [ "$BT_STATUS" != "OK" ]; then
+            echo "Error [SonarCloud API Status: $BT_STATUS]"
+            exit 1
+          fi      
       
